### ISSUE TITLE
I can't import the .apkm file 

### ISSUE THREAD

**Issue by SrPokz** [vinegarhq/sober#111]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

So, I just downloaded this on my computer (running xubuntu, if that matters) but I can't import the .apkm file. When I click on "Select Application Bundle" the file explorer just won't pop up, and after some seconds I'm told that i chose an "Invalid Bundle". So yeah, help lmao

**Comment by 0vf** [comment]
can you give a video of this problem?

**Comment by km9l** [comment]
send output of `systemctl status --user xdg-desktop-portal-*`

**Comment by Nezfebud-Demetreus** [comment]
● xdg-desktop-portal-gnome.service - Portal service (GNOME implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-gnome.service; static)
     Active: active (running) since Fri 2024-08-16 18:17:37 UTC; 1h 26min ago
   Main PID: 3257 (xdg-desktop-por)
      Tasks: 6 (limit: 19012)
     Memory: 18.7M (peak: 20.0M)
        CPU: 402ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/xdg-desktop-portal-gnome.service
             └─3257 /usr/libexec/xdg-desktop-portal-gnome
![sss](https://github.com/user-attachments/assets/b87cb933-f453-4c92-a3fa-95b2ddff98d8)

**Comment by km9l** [comment]
> ● xdg-desktop-portal-gnome.service - Portal service (GNOME implementation) Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-gnome.service; static) Active: active (running) since Fri 2024-08-16 18:17:37 UTC; 1h 26min ago Main PID: 3257 (xdg-desktop-por) Tasks: 6 (limit: 19012) Memory: 18.7M (peak: 20.0M) CPU: 402ms CGroup: /user.slice/user-1000.slice/[user@1000.service](mailto:user@1000.service)/app.slice/xdg-desktop-portal-gnome.service └─3257 /usr/libexec/xdg-desktop-portal-gnome ![sss](https://private-user-images.githubusercontent.com/126713212/358699299-b87cb933-f453-4c92-a3fa-95b2ddff98d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4Mzc5NDcsIm5iZiI6MTcyMzgzNzY0NywicGF0aCI6Ii8xMjY3MTMyMTIvMzU4Njk5Mjk5LWI4N2NiOTMzLWY0NTMtNGM5Mi1hM2ZhLTk1YjJkZGZmOThkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQxOTQ3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODA1ZmRiNDNmZDFiYjFiMjlmMzZlOTgyZjYyNGI3MmU4ODljNjc0MWE2ZjdiNzI3ZGE4ZjhmNDcyZDE4ZmFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FYxZzMMay-hmCqPoLOU8niKn7_0pADywc7FfpwAXm2M)

i assume this is the output after running sober at least once

`flatpak run --verbose --log-session-bus org.vinegarhq.Sober` output?

**Comment by sheikh1233** [comment]
i am having the same issue on gentoo, using xdg-desktop-portal-hyprland, with xdg-desktop-portal-gtk providing the file picker.

**Comment by sheikh1233** [comment]
`F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/Ahnaf/.local/share/flatpak
F: Opening user flatpak installation at path /home/Ahnaf/.local/share/flatpak
F: Opening user flatpak installation at path /home/Ahnaf/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/46/cbd6597a7a131f6ddfe5db99c3f761dc8921b81b7b05a5e210924e6b5b5f53f4/files/lib32 does not exist
F: Cleaning up unused container id 2988041901
F: Cleaning up per-app-ID state for org.vinegarhq.Sober
F: Allocated instance id 3578065109
F: Add defaults in dir /org/vinegarhq/Sober/
F: Add locks in dir /org/vinegarhq/Sober/
F: Allowing host-fs access
F: Allowing wayland access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/Ahnaf/.config/pulse/client.conf': Error opening file /home/Ahnaf/.config/pulse/client.conf: No such file or directory
F: Failed to run in transient scope: No systemd user session available, cgroups not available
F: Running 'bwrap --args 40 -- xdg-dbus-proxy --args=42'
F: Running 'bwrap --args 40 -- sober'
Roblox installation is required, starting onboarding flow UI...
C1: -> org.freedesktop.DBus call org.freedesktop.DBus.Hello at /org/freedesktop/DBus
C2: -> org.freedesktop.DBus fake wildcarded AddMatch for org.freedesktop.portal
C3: -> org.freedesktop.DBus fake wildcarded AddMatch for org.mpris.MediaPlayer2.org.vinegarhq.Sober
C4: -> org.freedesktop.DBus fake wildcarded AddMatch for org.vinegarhq.Sober
C5: -> org.freedesktop.DBus fake ListNames
B1: <- org.freedesktop.DBus return from C1
B2: <- org.freedesktop.DBus signal org.freedesktop.DBus.NameAcquired at /org/freedesktop/DBus
B3: <- org.freedesktop.DBus return from C2
*SKIPPED*
B4: <- org.freedesktop.DBus return from C3
*SKIPPED*
B5: <- org.freedesktop.DBus return from C4
*SKIPPED*
B6: <- org.freedesktop.DBus return from C5
C6: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.DBus
C7: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.Desktop
C8: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.Documents
*SKIPPED*
B7: <- org.freedesktop.DBus return from C6
*SKIPPED*
B8: <- org.freedesktop.DBus return from C7
*SKIPPED*
B9: <- org.freedesktop.DBus return from C8
*SKIPPED*
C9: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C10: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
C11: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C12: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C13: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
B10: <- org.freedesktop.DBus return from C9
B11: <- org.freedesktop.DBus return from C10
B12: <- org.freedesktop.DBus return from C11
B13: <- org.freedesktop.DBus return from C12
B14: <- org.freedesktop.DBus return from C13
C14: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
B15: <- org.freedesktop.DBus return from C14
C15: -> :1.11 call org.freedesktop.DBus.Properties.GetAll at /org/freedesktop/portal/desktop
B1233: <- :1.11 return from C15
C16: -> :1.11 call org.freedesktop.portal.Settings.ReadAll at /org/freedesktop/portal/desktop
B1247: <- :1.11 return from C16
C17: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C18: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C19: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
B16: <- org.freedesktop.DBus return from C17
B17: <- org.freedesktop.DBus return from C18
B18: <- org.freedesktop.DBus return from C19
C20: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
B19: <- org.freedesktop.DBus return from C20
C21: -> :1.11 call org.freedesktop.DBus.Properties.GetAll at /org/freedesktop/portal/desktop
B1249: <- :1.11 return from C21
C22: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C23: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
Filtering message due to arg0 org.gtk.vfs.Daemon, policy: 0 (required 2)
*HIDDEN* (ping)
B20: <- org.freedesktop.DBus return from C22
B21: <- (no sender) return from C23
*REWRITTEN*
C24: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
Filtering message due to arg0 org.gtk.vfs.Daemon, policy: 0 (required 1)
B22: <- (no sender) return from C24
*REWRITTEN*
C25: -> org.gtk.vfs.Daemon call org.gtk.vfs.MountTracker.ListMountableInfo at /org/gtk/vfs/mounttracker
*HIDDEN* (ping)
B23: <- (no sender) return from C25
*REWRITTEN*
C26: -> org.freedesktop.DBus call org.freedesktop.DBus.RemoveMatch at /org/freedesktop/DBus
B24: <- org.freedesktop.DBus return from C26
C27: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
B25: <- org.freedesktop.DBus return from C27
C28: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
B26: <- org.freedesktop.DBus return from C28
C29: -> :1.11 call org.freedesktop.DBus.Properties.GetAll at /org/freedesktop/portal/desktop
B1250: <- :1.11 return from C29
C30: -> :1.11 call org.freedesktop.portal.Settings.Read at /org/freedesktop/portal/desktop
B1252: <- :1.11 return from C30
C31: -> :1.11 call org.freedesktop.portal.Settings.Read at /org/freedesktop/portal/desktop
B1254: <- :1.11 return error org.freedesktop.portal.Error.NotFound from C31
C32: -> :1.11 call org.freedesktop.portal.Settings.Read at /org/freedesktop/portal/desktop
B1256: <- :1.11 return from C32
C1: -> org.freedesktop.DBus call org.freedesktop.DBus.Hello at /org/freedesktop/DBus
C2: -> org.freedesktop.DBus fake wildcarded AddMatch for org.freedesktop.portal
C3: -> org.freedesktop.DBus fake wildcarded AddMatch for org.mpris.MediaPlayer2.org.vinegarhq.Sober
C4: -> org.freedesktop.DBus fake wildcarded AddMatch for org.vinegarhq.Sober
C5: -> org.freedesktop.DBus fake ListNames
B1: <- org.freedesktop.DBus return from C1
B2: <- org.freedesktop.DBus signal org.freedesktop.DBus.NameAcquired at /org/freedesktop/DBus
B3: <- org.freedesktop.DBus return from C2
*SKIPPED*
B4: <- org.freedesktop.DBus return from C3
*SKIPPED*
B5: <- org.freedesktop.DBus return from C4
*SKIPPED*
B6: <- org.freedesktop.DBus return from C5
C6: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.DBus
C7: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.Desktop
C8: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.Documents
*SKIPPED*
B7: <- org.freedesktop.DBus return from C6
*SKIPPED*
B8: <- org.freedesktop.DBus return from C7
*SKIPPED*
B9: <- org.freedesktop.DBus return from C8
*SKIPPED*
C9: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C10: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
C11: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C12: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
B10: <- org.freedesktop.DBus return from C9
B11: <- org.freedesktop.DBus return from C10
B12: <- org.freedesktop.DBus return from C11
B13: <- org.freedesktop.DBus return from C12
C13: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
B14: <- org.freedesktop.DBus return from C13
C14: -> :1.11 call org.freedesktop.portal.NetworkMonitor.GetStatus at /org/freedesktop/portal/desktop
B1258: <- :1.11 return from C14
C15: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C16: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C17: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
B15: <- org.freedesktop.DBus return from C15
B16: <- org.freedesktop.DBus return from C16
B17: <- org.freedesktop.DBus return from C17
C18: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
B18: <- org.freedesktop.DBus return from C18
C19: -> :1.11 call org.freedesktop.DBus.Properties.GetAll at /org/freedesktop/portal/desktop
B1259: <- :1.11 return from C19
C20: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C21: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
Filtering message due to arg0 org.gtk.vfs.Daemon, policy: 0 (required 2)
*HIDDEN* (ping)
B19: <- org.freedesktop.DBus return from C20
B20: <- (no sender) return from C21
*REWRITTEN*
C22: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
Filtering message due to arg0 org.gtk.vfs.Daemon, policy: 0 (required 1)
B21: <- (no sender) return from C22
*REWRITTEN*
C23: -> org.gtk.vfs.Daemon call org.gtk.vfs.MountTracker.ListMountableInfo at /org/gtk/vfs/mounttracker
*HIDDEN* (ping)
B22: <- (no sender) return from C23
*REWRITTEN*
C24: -> org.freedesktop.DBus call org.freedesktop.DBus.RemoveMatch at /org/freedesktop/DBus
B23: <- org.freedesktop.DBus return from C24
C33: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C34: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
B27: <- org.freedesktop.DBus return from C33
B28: <- org.freedesktop.DBus return from C34
C35: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C36: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
Filtering message due to arg0 org.gtk.vfs.Daemon, policy: 0 (required 2)
*HIDDEN* (ping)
B29: <- org.freedesktop.DBus return from C35
B30: <- (no sender) return from C36
*REWRITTEN*
C37: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
Filtering message due to arg0 org.gtk.vfs.Daemon, policy: 0 (required 1)
B31: <- (no sender) return from C37
*REWRITTEN*
C38: -> org.gtk.vfs.Daemon call org.gtk.vfs.Daemon.ListMonitorImplementations at /org/gtk/vfs/Daemon
*HIDDEN* (ping)
B32: <- (no sender) return from C38
*REWRITTEN*
C39: -> org.freedesktop.DBus call org.freedesktop.DBus.RemoveMatch at /org/freedesktop/DBus
B33: <- org.freedesktop.DBus return from C39
C40: -> org.freedesktop.portal.Desktop call org.freedesktop.portal.FileChooser.OpenFile at /org/freedesktop/portal/desktop
B1264: <- :1.11 return from C40
B1266: <- :1.11 signal org.freedesktop.portal.Request.Response at /org/freedesktop/portal/desktop/request/1_398/gtk1090953265
`
This is the log of running with --verbose and --log-session-bus

**Comment by Nezfebud-Demetreus** [comment]
output of flatpak run --verbose --log-session-bus org.vinegarhq.Sober

flatpak run --verbose --log-session-bus org.vinegarhq.Sober
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/noname/.local/share/flatpak
F: Opening user flatpak installation at path /home/noname/.local/share/flatpak
F: Skipping parental controls check for app/org.vinegarhq.Sober/x86_64/master since parental controls are disabled globally
F: Opening user flatpak installation at path /home/noname/.local/share/flatpak
F: Unknown device type input
F: /home/noname/.local/share/flatpak/runtime/org.gnome.Platform/x86_64/46/4a418b5001f574aacf01a10206f7810922aa8da23400e2b3f446733c96811228/files/lib32 does not exist
F: Allocated instance id 2743621843
F: Add defaults in dir /org/vinegarhq/Sober/
F: Add locks in dir /org/vinegarhq/Sober/
F: Disallowing ipc access
F: Allowing dri access
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/noname/.config/pulse/client.conf': Error opening file /home/noname/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 41 -- xdg-dbus-proxy --args=43'
F: Running 'bwrap --args 41 -- sober'
Roblox installation is required, starting onboarding flow UI...
C1: -> org.freedesktop.DBus call org.freedesktop.DBus.Hello at /org/freedesktop/DBus
C2: -> org.freedesktop.DBus fake wildcarded AddMatch for org.freedesktop.portal
C3: -> org.freedesktop.DBus fake wildcarded AddMatch for org.mpris.MediaPlayer2.org.vinegarhq.Sober
C4: -> org.freedesktop.DBus fake wildcarded AddMatch for org.vinegarhq.Sober
C5: -> org.freedesktop.DBus fake ListNames
B1: <- org.freedesktop.DBus return from C1
B2: <- org.freedesktop.DBus signal org.freedesktop.DBus.NameAcquired at /org/freedesktop/DBus
B3: <- org.freedesktop.DBus return from C2
*SKIPPED*
B4: <- org.freedesktop.DBus return from C3
*SKIPPED*
B5: <- org.freedesktop.DBus return from C4
*SKIPPED*
B6: <- org.freedesktop.DBus return from C5
C6: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.DBus
C7: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.Desktop
C8: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.Documents
C9: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.IBus
*SKIPPED*
B7: <- org.freedesktop.DBus return from C6
*SKIPPED*
B8: <- org.freedesktop.DBus return from C7
*SKIPPED*
B9: <- org.freedesktop.DBus return from C8
*SKIPPED*
B10: <- org.freedesktop.DBus return from C9
*SKIPPED*
C10: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C11: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
B11: <- org.freedesktop.DBus return from C10
B12: <- org.freedesktop.DBus return from C11
C12: -> org.freedesktop.DBus call org.freedesktop.DBus.GetId at /org/freedesktop/DBus
B13: <- org.freedesktop.DBus return from C12
C13: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C14: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
C15: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C16: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C17: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
B14: <- org.freedesktop.DBus return from C13
B15: <- org.freedesktop.DBus return from C14
B16: <- org.freedesktop.DBus return from C15
B17: <- org.freedesktop.DBus return from C16
B18: <- org.freedesktop.DBus return from C17
C18: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
B19: <- org.freedesktop.DBus return from C18
C19: -> :1.91 call org.freedesktop.DBus.Properties.GetAll at /org/freedesktop/portal/desktop
B183: <- :1.91 return from C19
C20: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C21: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
Filtering message due to arg0 org.gtk.vfs.Daemon, policy: 0 (required 2)
*HIDDEN* (ping)
B20: <- org.freedesktop.DBus return from C20
B21: <- (no sender) return from C21
*REWRITTEN*
C22: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
Filtering message due to arg0 org.gtk.vfs.Daemon, policy: 0 (required 1)
B22: <- (no sender) return from C22
*REWRITTEN*
C23: -> org.gtk.vfs.Daemon call org.gtk.vfs.MountTracker.ListMountableInfo at /org/gtk/vfs/mounttracker
*HIDDEN* (ping)
B23: <- (no sender) return from C23
*REWRITTEN*
C24: -> org.freedesktop.DBus call org.freedesktop.DBus.RemoveMatch at /org/freedesktop/DBus
B24: <- org.freedesktop.DBus return from C24
C25: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C26: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C27: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
B25: <- org.freedesktop.DBus return from C25
B26: <- org.freedesktop.DBus return from C26
B27: <- org.freedesktop.DBus return from C27
C28: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
B28: <- org.freedesktop.DBus return from C28
C29: -> :1.91 call org.freedesktop.DBus.Properties.GetAll at /org/freedesktop/portal/desktop
B184: <- :1.91 return from C29
C30: -> :1.91 call org.freedesktop.portal.Settings.Read at /org/freedesktop/portal/desktop
B187: <- :1.91 return from C30
C31: -> :1.91 call org.freedesktop.portal.Settings.Read at /org/freedesktop/portal/desktop
B189: <- :1.91 return from C31
C1: -> org.freedesktop.DBus call org.freedesktop.DBus.Hello at /org/freedesktop/DBus
C2: -> org.freedesktop.DBus fake wildcarded AddMatch for org.freedesktop.portal
C3: -> org.freedesktop.DBus fake wildcarded AddMatch for org.mpris.MediaPlayer2.org.vinegarhq.Sober
C4: -> org.freedesktop.DBus fake wildcarded AddMatch for org.vinegarhq.Sober
C5: -> org.freedesktop.DBus fake ListNames
B1: <- org.freedesktop.DBus return from C1
B2: <- org.freedesktop.DBus signal org.freedesktop.DBus.NameAcquired at /org/freedesktop/DBus
B3: <- org.freedesktop.DBus return from C2
*SKIPPED*
B4: <- org.freedesktop.DBus return from C3
*SKIPPED*
B5: <- org.freedesktop.DBus return from C4
*SKIPPED*
B6: <- org.freedesktop.DBus return from C5
C6: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.DBus
C7: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.Desktop
C8: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.Documents
C9: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.IBus
*SKIPPED*
C10: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C11: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
C12: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C13: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
B7: <- org.freedesktop.DBus return from C6
*SKIPPED*
B8: <- org.freedesktop.DBus return from C7
*SKIPPED*
B9: <- org.freedesktop.DBus return from C8
*SKIPPED*
B10: <- org.freedesktop.DBus return from C9
*SKIPPED*
B11: <- org.freedesktop.DBus return from C10
B12: <- org.freedesktop.DBus return from C11
B13: <- org.freedesktop.DBus return from C12
B14: <- org.freedesktop.DBus return from C13
C14: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
B15: <- org.freedesktop.DBus return from C14
C15: -> :1.91 call org.freedesktop.portal.NetworkMonitor.GetStatus at /org/freedesktop/portal/desktop
B191: <- :1.91 return from C15
B1444: <- :1.39 call org.gtk.Actions.DescribeAll at /org/vinegarhq/Sober
B1448: <- :1.39 call org.freedesktop.DBus.Properties.GetAll at /org/vinegarhq/Sober
C32: -> :1.39 return from B1444
C33: -> :1.39 return from B1448
B1453: <- :1.39 call org.gtk.Actions.DescribeAll at /org/vinegarhq/Sober/window/2
C34: -> :1.39 return from B1453
C16: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C17: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C18: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
B16: <- org.freedesktop.DBus return from C16
B17: <- org.freedesktop.DBus return from C17
B18: <- org.freedesktop.DBus return from C18
C19: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
B19: <- org.freedesktop.DBus return from C19
C20: -> :1.91 call org.freedesktop.DBus.Properties.GetAll at /org/freedesktop/portal/desktop
B192: <- :1.91 return from C20
C21: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C22: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
Filtering message due to arg0 org.gtk.vfs.Daemon, policy: 0 (required 2)
*HIDDEN* (ping)
B20: <- org.freedesktop.DBus return from C21
B21: <- (no sender) return from C22
*REWRITTEN*
C23: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
Filtering message due to arg0 org.gtk.vfs.Daemon, policy: 0 (required 1)
B22: <- (no sender) return from C23
*REWRITTEN*
C24: -> org.gtk.vfs.Daemon call org.gtk.vfs.MountTracker.ListMountableInfo at /org/gtk/vfs/mounttracker
*HIDDEN* (ping)
B23: <- (no sender) return from C24
*REWRITTEN*
C25: -> org.freedesktop.DBus call org.freedesktop.DBus.RemoveMatch at /org/freedesktop/DBus
B24: <- org.freedesktop.DBus return from C25
C35: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C36: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
Filtering message due to arg0 org.gtk.vfs.Daemon, policy: 0 (required 2)
*HIDDEN* (ping)
B29: <- org.freedesktop.DBus return from C35
B30: <- (no sender) return from C36
*REWRITTEN*
C37: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
Filtering message due to arg0 org.gtk.vfs.Daemon, policy: 0 (required 1)
B31: <- (no sender) return from C37
*REWRITTEN*
C38: -> org.gtk.vfs.Daemon call org.gtk.vfs.Daemon.ListMonitorImplementations at /org/gtk/vfs/Daemon
*HIDDEN* (ping)
B32: <- (no sender) return from C38
*REWRITTEN*
C39: -> org.freedesktop.DBus call org.freedesktop.DBus.RemoveMatch at /org/freedesktop/DBus
B33: <- org.freedesktop.DBus return from C39
C40: -> org.freedesktop.portal.Desktop call org.freedesktop.portal.FileChooser.OpenFile at /org/freedesktop/portal/desktop
B197: <- :1.91 return from C40
B203: <- :1.91 signal org.freedesktop.portal.Request.Response at /org/freedesktop/portal/desktop/request/1_110/gtk1869789490
Roblox installation was closed by user.

**Comment by ognevny** [comment]
.apkm files are actually .zip archives. just rename the bundle to give it .zip extension and use `unzip` to extract

**Comment by apprehensions** [comment]
Which you are not reccomended to do, as sober wants a *bundle*.

**Comment by ognevny** [comment]
> Which you are not reccomended to do, as sober wants a *bundle*.

bundle never worked for me. that's the only way it's installed

**Comment by Piecuuu** [comment]
> just rename the bundle to give it .zip extension and use `unzip` to extract
You don't need to rename it. `unzip` will recognize it and unzip it anyways.
