### ISSUE TITLE
Sober crashes when opening certain roblox games.

### ISSUE THREAD

**Issue by Crostrix** [vinegarhq/sober#221]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

When opening a roblox game. Sober just crashes. I went in and did a manual Sober run. But nothing was wrong. No error/warnings.

### Roblox Experience link

https://www.roblox.com/games/3421472751/Stateview-Prison

**Comment by yoshiweegee** [comment]
Same happens for me. The crash visually is identical to #205 for me.

**Comment by ARareUsername** [comment]
I managed to fix this by doing a complete reinstall of sober. In fact, I had to install using the flatpak file instead of the flatpak link on the website. I'm not sure if that changed anything but I figured some internal files were broken with the specific games I was trying to launch causing a full freeze. 

In my case, the games that were freezing were only games that I had already previously ran so that's how I came up with a complete reinstall.

For some reason, just doing a flatpak uninstall wasn't sufficient and I was still logged in after a reinstall. You have to make sure you run `flatpak uninstall --delete-data org.vinegarhq.Sober` 

Reinstall sober, try the link or the flatpak file on the website.

Launched Sober using the --boostrap flag to completely reinstall the APK package too using `flatpak run org.vinegarhq.Sober --bootstrap`

Hope this helps!

**Comment by yoshiweegee** [comment]
A full reinstall with `--delete-data` worked for me as well. I didn't need to use `--bootstrap` because the APK data was deleted in the uninstall.

If the same fix works for Crostrix, I'll redirect my issue to here and close it as a duplicate, since there's more information here now.

Possibly of note is that between the previous and current versions of Sober, I had upgraded my OS from Linux Mint 21.3 to 22. Sober was still working fine before the Sober update, so perhaps Flatpak was confused in some way when it updated Sober?

**Comment by Crostrix** [comment]
Hi, Thanks! This worked!

Closing the issue now

**Comment by yoshiweegee** [comment]
@Crostrix I consistently encounter this issue after playing one session of Ghostly Manor. Attempting to play the experience again causes the crash until I do another hard reinstall. Does this happen for you as well? If so, this issue should be reopened. If not, then it's specific to Ghostly Manor, and I'll reopen my issue.

**Comment by yoshiweegee** [comment]
The recent update did not fix this issue for me. Effects are the same as my previous comment.

**Comment by Yello856** [comment]
> Hey,
> 
> After recent update i encounter the same issue again :(
> 
> Can't fix it via that method.

Did you figure it out

**Comment by yoshiweegee** [comment]
According to https://github.com/vinegarhq/sober/issues/205#issuecomment-2392814060, the bug was identified and should be fixed in the next update.
