### ISSUE TITLE
Will Sober ever be open sourced?

### ISSUE THREAD

**Issue by qtqgyt** [vinegarhq/sober#331]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

No

### Describe the Solution you'd Like

I figure that this probably has been asked before, but I can't find it on the issue tracker.

Will saber be open sourced?
That's all I want to know.

### Describe Alternatives you've considered

N/A

**Comment by kirbix12** [comment]
Sober being open source may change in the future, but due to circumstances regarding what happened while Roblox unblocked Wine, the Sober developers do not want to risk making the same mistake, even if it means hosting the code behind doors.

For further context, they do not want to risk abusers take upon the code to abuse the platform, given Roblox on Android is without Hyperion ever since the anti-cheat's inception.

**Comment by apprehensions** [comment]
> I have confirmed that this should be classified as an enhancement rather than a bug/feature.

Not an enhancement to Sober.

**Comment by DrymarchonShaun** [comment]
Maybe worth adding something to the effect of @kirbix12's answer to the README? Pinning a locked issue with the explanation could work too.

Might stop a few more of the people who'll inevitably miss it in the website FAQ.
