### ISSUE TITLE
Migrate Sober to Android Translation Layer

### ISSUE THREAD

**Issue by Covkie** [vinegarhq/sober#376]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

Currently Sober acts as a Downloader, custom Patcher and most importantly a Translation layer between the Android APIs Roblox uses and Linux. 

The latter is a development burden and the work can only ever be used for Roblox.

### Describe the Solution you'd Like

Move the translation patches to Android Translation Layer. Once done this would make Sober like how Vinegar was – GUI manager for a translation layer(wine) with options for patches. Doing so would also help the upstream project mature & grow(also other Android apps would be closer to working on Linux).

might also enable faster version changes.

### Describe Alternatives you've considered

Don't? Lol

### Additional context

https://gitlab.com/android_translation_layer/android_translation_layer

https://flathub.org/apps/net.newpipe.NewPipe
https://github.com/TeamNewPipe/NewPipe/issues/11597

**Comment by tunis4** [comment]
there's not much we can contribute to the android translation layer since we mostly only implement the specific things that roblox needs. i think the only stuff we have that could be useful are the AAudio and ACamera implementations for voice chat, but even those can't be ported directly since its for SDL instead of whatever that project is using.

as for making sober use the android translation layer, i think it would take a lot of work and it would only make things worse. sober is designed to run only roblox and make it feel as close to a native client as possible. using this project would make the experience way less refined (a lot of sober's code is roblox-specific workarounds) and more heavy (for example that project runs an entire java virtual machine while sober doesn't need to)

> might also enable faster version changes.

no, it wouldn't help version changes at all.
