### ISSUE TITLE
Weird mouse grabbing on Phantom Forces

### ISSUE THREAD

**Issue by yuki-was-taken** [vinegarhq/sober#5]
When playing Phantom Forces, roblox grabs my cursor and allows me to look around normally, but when I go to the main menu/open the roblox menu, my cursor is still locked to the centre of the screen. There isn't any way to free my cursor without leaving the game.

**Comment by km9l** [comment]
this is because mouse locking is broken in modals

it's hard to fix, but we'll try our best

**Comment by teamkill3d** [comment]
i have a similar bug in phighting, whenever a game server gets shutdown, i am unable to leave the game without alt-f4ing because the mouse is still locked

**Comment by Myrdincx** [comment]
I believe a quick workaround for now is pressing `F1` to unlock the cursor and pressing `F1` to re-enable it.
This solution comes [from this post on discord](https://discord.com/channels/1069506340973707304/1268755260072267888/1269355829769797694)

**Comment by km9l** [comment]
> I believe a quick workaround for now is pressing `F1` to unlock the cursor and pressing `F1` to re-enable it.

correct, this was recently added in into sober

**Comment by lucasmz-dev** [comment]
Is this the same issue where if you're in first camera mode and a GUI appears it doesn't seem to unlock the mouse? Unsure if I should open an issue about it. Need to try the F1 thing soon

**Comment by tunis4** [comment]
> Is this the same issue where if you're in first camera mode and a GUI appears it doesn't seem to unlock the mouse? Unsure if I should open an issue about it. Need to try the F1 thing soon

yes it is

**Comment by dakshshrivastav** [comment]
i'm having the inverse of this issue when i use `gamescope` to run sober 

(sober by itself works perfectly fine but for performance reasons i need to upscale from 720p rather than run 1080p native)

the cursor works fine on the menus and stuff but as soon as i enter the game (phantom forces in this case), the cursor is locked to the top of the screen and returns back to the top of the screen no matter how much you try.

i have tried pressing f1 to unlock and re-enable the cursor to no avail.

here's the command i'm using to run sober.

```
❯ flatpak run --command=/usr/lib/extensions/vulkan/gamescope/bin/gamescope \
org.vinegarhq.Sober \
-f \
-w 1280 -h 720 \
-W 1920 -H 1080 \
-F fsr \
-- sober
```
