### ISSUE TITLE
VR Support?

### ISSUE THREAD

**Issue by AngelBePro** [vinegarhq/sober#500]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

With Sober existing, I rarely use windows. VR support on linux isn't that good, but its there. When I tried using steamvr with sober in a vr "experience", nothing happened.

### Describe the Solution you'd Like

Standalone headsets often run android so maybe a android package for roblox will have the needed apis for vr 

### Describe Alternatives you've considered

using windows to play roblox vr defies the purpose of even sober.

### Additional context

I apologize if there is somehow VR and I am just dumb, and I hope that me reporting this as a feature/enhancement is right.

**Comment by tunis4** [comment]
one of the developers wanted to add vr support but there were many issues. the normal android apk doesn't support vr (the code for using vr apis was not compiled). the quest apk has vr support but it doesn't have a x86_64 build, its arm only. 

we had arm support by code translation in the early days of sober before roblox started releasing x86_64 apks. we tried to use the old arm translation code to run the quest apk but it didn't even launch due to many issues. and even if we did get the quest apk working it would have horrible performance due to the arm translation overhead, which is especially bad for vr.

we looked into manually adding the vr api code to the normal android apk since a lot of the vr logic code was left in, but we couldn't find any straightforward way of doing it. so it would take an insane amount of time and effort to get it working. which is definitely not worth it for a feature that only a few players will ever use.

so its likely not going to happen unless roblox decides to add proper vr support to their normal android apks or makes a x86_64 build of the quest apk (which wouldn't make any sense since it's specifically for an arm device).

**Comment by AngelBePro** [comment]
> one of the developers wanted to add vr support but there were many issues. the normal android apk doesn't support vr (the code for using vr apis was not compiled). the quest apk has vr support but it doesn't have a x86_64 build, its arm only.
> 
> we had arm support by code translation in the early days of sober before roblox started releasing x86_64 apks. we tried to use the old arm translation code to run the quest apk but it didn't even launch due to many issues. and even if we did get the quest apk working it would have horrible performance due to the arm translation overhead, which is especially bad for vr.
> 
> we looked into manually adding the vr api code to the normal android apk since a lot of the vr logic code was left in, but we couldn't find any straightforward way of doing it. so it would take an insane amount of time and effort to get it working. which is definitely not worth it for a feature that only a few players will ever use.
> 
> so its likely not going to happen unless roblox decides to add proper vr support to their normal android apks or makes a x86_64 build of the quest apk (which wouldn't make any sense since it's specifically for an arm device).

I wasn't able to find any information and with this I can know that there was atleast an attempt at making sober work with vr. Thanks!
